language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_06ae616e8cd6_key -iv $encrypted_06ae616e8cd6_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d


